/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gnc.evaluator;

import java.util.*;


public class App {

    public static void main(String[] args) {

        System.out.println("---> STARTING GN&C EVALUATOR");








    }
}
